#!/bin/sh -ex

#
# Not all of these steps are verified yet.
#

#
# Oracle installer requires /sbin/chkconfig
#

cat << 'EOF' > /sbin/chkconfig
#!/bin/bash
# Oracle 11gR2 XE installer chkconfig hack for Ubuntu
file=/etc/init.d/oracle-xe

if [[ ! `tail -n1 $file | grep INIT` ]]; then
  echo >> $file
  echo '### BEGIN INIT INFO' >> $file
  echo '# Provides: OracleXE' >> $file
  echo '# Required-Start: $remote_fs $syslog' >> $file
  echo '# Required-Stop: $remote_fs $syslog' >> $file
  echo '# Default-Start: 2 3 4 5' >> $file
  echo '# Default-Stop: 0 1 6' >> $file
  echo '# Short-Description: Oracle 11g Express Edition' >> $file
  echo '### END INIT INFO' >> $file
fi

update-rc.d shm_load defaults
update-rc.d oracle-xe defaults 80 01
EOF

chmod 755 /sbin/chkconfig

#
#
#

ln -s /usr/bin/awk /bin/awk
#mkdir -p /var/lock/subsys
## TODO: the file is not created
#touch /var/lock/subsys/listener

#
# Swap requirements:
# http://docs.oracle.com/cd/E17781_01/install.112/e18802/toc.htm
# -> 2.1.2 Swap Space Requirements
# https://wiki.debian.org/Swap
# TODO: modify swap partition instead
# TODO: fulfilled when disk size > 20GB in VirtualBox
# TODO: but how this should be really done ?
#

#
# /dev/shm
# Oracle doesn't like debian's /dev/shm so we have to 
# re-create it in every boot
#

cat << 'EOF' > /etc/init.d/shm_load
#!/bin/sh

### BEGIN INIT INFO
# Provides:             shm_load
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    /dev/shm for Oracle XE
### END INIT INFO

case "$1" in
start) mkdir -p /var/lock/subsys 2>/dev/null
       touch /var/lock/subsys/listener
       mount -o remount /dev/shm
       rm /dev/shm 2>/dev/null
       mkdir /dev/shm 2>/dev/null
       mount -t tmpfs shmfs -o size=2048m /dev/shm ;;
*) echo nothing
   exit 1 ;;
esac

exit 0
EOF

chmod 755 /etc/init.d/shm_load
